hydra:
  run:
    dir: .
batch_sizes: [256, 128, 64]
batch_size: 256
num_epochs: 200
num_eval_epochs: 50
lambda_param: 25.0
mu_param: 25.0
nu_param: 1
lr_vicreg: 1e-5
lr_linear: 1e-4
checkpoint_dir: "linear/128"
backbone: "resnet18" #или resnet50
projection_head_dims: [512, 512, 512]
probe: "linear"  # или "online"
loss: "biased" #или unbiased

