hydra:
  run:
    dir: .
batch_sizes: [256, 128, 64, 32, 16, 8]
batch_size: 256
batch_size_evaluate: 64
num_epochs: 100
num_eval_epochs: 30
sim_coeff: 25.0
std_coeff: 25.0
cov_coeff: 1
lr_vicreg: 2e-4
lr_linear: 2e-2
backbone: "resnet18" #или resnet50
projection_head_dims: [512, 512, 512]
probe: "linear"  # или "online"
loss: "unbiased" #или unbiased
batch_size_sharing: False

